### ISSUE TITLE
Searching for hashid's with the ModelAdmin's 'search_fields' feature?

### ISSUE THREAD

**Issue by Bartvds** [nshafer/django-hashid-field#13] opened 2017-09-06 12:13 UTC
It would be very useful for our daily operations if we could search the hashed value in the standard ModelAdmin search widget.

I naively tried adding the field name to `search_fields` but it doesn't find the items I know are there. This was with an HashidAutoField with primary, salt and alphabet all set.

I've spend some downtime looking into it, and found `ModelAdmin.get_search_results` in the docs, and I can make this search work by implementing it like this:

````python
def get_search_results(self, request, queryset, search_term):
    queryset, use_distinct = super().get_search_results(request, queryset, search_term)
    queryset |= self.model.objects.filter(id=search_term)
    return queryset, use_distinct
````

What is weird about it that my code doesn't do any decoding; the regular queryset lookup on the field does it already. 

So now I wonder if we can make it so we don't need to cart this overridden method around but just use the field name in the `search_fields`?

**Comment by nshafer** [comment] 2017-09-14 17:01
The issue is that the default `ModelAdmin.get_search_results` implementation doesn't do an exact lookup like you're doing, instead it does an `__icontains` by default. So this will probably be fixed in the same way as #10 which is to implement custom lookup handling for the field, so all of those different lookups succeed. The issue is figuring out how to handle any of the case-insensitive lookups (`iexact`, `icontains` `istartswith`, `iendswith`, etc) and also the partial lookup types themselves, since hashids are very much case-sensitive, and we don't store the strings, so do partial matches is problematic.

**Comment by maxmalysh** [comment] 2017-09-19 04:17
Is there a reason why we don't just use CharField as a base class? This solves most of the string-related issues, and is much more explicit and closer to reality.

**Comment by nshafer** [comment] 2017-09-19 04:43
I originally developed it for a project to be a drop-in replacement for AutoFields, without having to change the underlying DB field and migrate the data (and all the foreign keys as well), so I went with storing it as an integer and basing it off of IntegerField. I actually have a solution to this problem working in the `lookups` branch, but I need to hack on it a bit more to get it compatible with older version of Django (only works with 1.11 right now). It supports all of the lookups needed for the search functionality, but does so by basically making *exact*, *iexact*, *contains* and *icontains* all do the same thing, which is an *exact* search. *startswith* and *endswith* won't be supported, and *in* lookups will work, and right now even work with subqueries. But the lookups system has been changing a lot since it was introduced in 1.7, and I didn't realize how unstable it was, so I'll need to write a lot more specific code to support all the versions instead of being able to just tie into the right place like I'm doing now for 1.11.

**Comment by nshafer** [comment] 2017-09-25 22:10
This should now work with version 1.3.0 without any extra code in your ModelAdmin classes.

**Closed by nshafer** 2017-09-25 22:10 UTC

**Comment by Bartvds** [comment] 2017-09-26 07:17
Very cool, thanks.

**Comment by adi-** [comment] 2019-07-15 14:35
Any plans to support partial lookups?

**Comment by nshafer** [comment] 2019-07-15 14:56
Unfortunately partial lookups are impossible with the way the module is implemented. Since it stores the field as an integer in the database, I would have to pull the id of every single row of the table into a list, convert all of them to hashid, then search in Python, so it would be way too slow for any table of decent size.

**Comment by adi-** [comment] 2019-07-15 15:09
hashids could be cached in DB... ;)

**Comment by nshafer** [comment] 2019-07-15 15:16
That is true, but outside the scope of the module. It would be possible to adapt it to use a varchar underneath, instead of integer, but I haven't seen enough of a use case to warrant the dev time. Why do you want partial searches? You can't do partial searches on integer IDs either.

**Comment by adi-** [comment] 2019-07-15 15:20
hashes are service order numbers in the system. They are 14 char string. Sometimes, users dictates them for our operators by phone. It would be easier to paste i.e. first 4 chars to search users' order.

**Comment by nshafer** [comment] 2019-07-15 15:23
You can add a CharField to the model and override `save()` to record the hashid from the HashidField, then do partial matches on that.

**Comment by adi-** [comment] 2019-07-15 15:35
I know, was curious if it is already planned ;)

**Comment by nshafer** [comment] 2019-07-15 16:14
Gotcha, not at the moment, sorry.
